apiVersion: v1
kind: Secret
metadata:
  name: fashion-secrets
type: Opaque
data:
  WANDB_API_KEY: "d2FuZGJfdjFfWDNkWndqdVlWb2RkWFRkVDlWRXJFZ0RQWmlZX1FtYXdWSWM4RzZkY2doYnA5dnlRU3ptR1NZb3FyUGdCMEpNcDJYVXVFa2sySEdDV3E="
